site_name: Apogee Playground Documentation
site_url: https://www.playapogee.app/
site_description: Get started with Apogee Playground app here
site_author: Apogee Code OÜ
repo_name: apogeecode/apogee-playground-docs
# repo_url: https://github.com/apogeecode/apogee-playground-docs
copyright: &copy 2021 Apogee Code OÜ. All rights reserved

plugins:
  - search
  - i18n:
      languages:
        en: "English"
        et: "Eesti"
        ru: "Pусский"
      default_language: 'en'
      no_translation:
        en: "This page has not been translated into English."
        et: "See leht ei ole tõlgitud eesti keelde."
        ru: "Эта страница не переведена на русский язык."
      translate_nav:
        en:
          Getting Started: "Getting Started"
          Exploring Expressions: "Exploring Expressions"
          Expressing Yourself: "Expressing Yourself"
          Features: "Features"
          Account: "Account"
          Safety: "Safety"
        et:
          Getting Started: "Getting Started"
          Exploring Expressions: "Exploring Expressions"
          Expressing Yourself: "Expressing Yourself"
          Features: "Features"
          Account: "Account"
          Safety: "Safety"
        ru:
          Getting Started: "Getting Started"
          Exploring Expressions: "Exploring Expressions"
          Expressing Yourself: "Expressing Yourself"
          Features: "Features"
          Account: "Account"
          Safety: "Safety"
  - minify:
      minify_html: true

nav:
    - index.md
    - index.et.md
    - faq.en.md
    - Getting Started: 
        - Getting_Started/index.en.md
        - Getting_Started/installation.en.md
        - Getting_Started/signup.en.md
        - Getting_Started/signin.en.md
        - Getting_Started/choosing_your_playground.en.md
        - Exploring Expressions: 
            - Getting_Started/Exploring_Expressions/index.en.md
            - Getting_Started/Exploring_Expressions/filtering_and_search.en.md
            - Getting_Started/Exploring_Expressions/requesting.en.md
            - Getting_Started/Exploring_Expressions/communicating.en.md
            - Getting_Started/Exploring_Expressions/having_session.en.md
            - Getting_Started/Exploring_Expressions/LORICE.en.md
            - Getting_Started/Exploring_Expressions/donating.en.md
            - Getting_Started/Exploring_Expressions/rating.en.md
        - Expressing Yourself: 
            - Getting_Started/Expressing_Yourself/index.en.md
            - Getting_Started/Expressing_Yourself/expressions.en.md
            - Getting_Started/Expressing_Yourself/requests.en.md
            - Getting_Started/Expressing_Yourself/communicating.en.md
            - Getting_Started/Expressing_Yourself/navigating.en.md
            - Getting_Started/Expressing_Yourself/having_session.en.md
            - Getting_Started/Expressing_Yourself/LORICE.en.md
            - Getting_Started/Expressing_Yourself/donating.en.md
            - Getting_Started/Expressing_Yourself/rating.en.md
    - Account: 
        - Account/updating_profile.en.md
        - Account/changing_password.en.md
        - Account/changing_pin.en.md
        - Account/signout.en.md
    - Features: 
        - Features/user_modes.en.md
        - Features/requests.en.md
        - Features/sessions.en.md
        - Features/donations.en.md
        - Features/ratings.en.md
        - Features/redemption.en.md
        - Features/referrals.en.md
        - Features/memberships.en.md
        - Safety: 
            - Features/Safety/sos.en.md
            - Features/Safety/index.en.md
            - Features/Safety/verification.en.md
            - Features/Safety/trusted_contacts.en.md
            - Features/Safety/pin_prompt.en.md
            - Features/Safety/silent_mode.en.md

theme:
  name: material
  language: en

  favicon: images/favicon.png
  logo: images/circle-black.svg

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - search.share
    - search.suggest
    - header.autohide
    - search.highlight
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-ZLFG32HBFF

  alternate:
    - name: English
      link: index.en/
      lang: en

    - name: Eesti
      link: index.et/
      lang: et

    - name: Pусский
      link: index.ru/
      lang: ru
  
  social:
    - icon: octicons/mail-24
      link: mailto:contact@apogee.codes
      name: Contact us

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/playapogee/
      name: PlayApogee on Instagram

    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/PlayApogee
      name: PlayApogee on Facebook

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PlayApogee
      name: PlayApogee on Twitter

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/playapogee
      name: PlayApogee on LinkedIn

    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@apogee_playground
      name: PlayApogee on TikTok

    - icon: fontawesome/brands/discord
      link: https://discord.gg/scpAjmsvb5
      name: PlayApogee on Discord

    - icon: fontawesome/brands/telegram
      link: https://t.me/apogeecode
      name: PlayApogee on Telegram
    
    - icon: fontawesome/brands/tumblr
      link: https://playapogee.tumblr.com/
      name: PlayApogee on Tumblr

markdown_extensions:
    - abbr
    - meta
    - def_list
    - attr_list
    - footnotes
    - admonition
    - md_in_html
    - pymdownx.mark
    - pymdownx.keys
    - pymdownx.caret
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.inlinehilite
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - toc:
        permalink: ⚓︎
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg