site_name: Apogee Playground Documentation
site_url: https://docs.playapogee.app/
repo_name: GitHub
repo_url: 
site_description: Get started with Apogee Playground app here...
site_author: Apogee Code OU
copyright: © 2021 Apogee Code OÜ. All rights reserved
theme: readthedocs